/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.JavaApplication2;

/**
 *
 * @author ep
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClerk = new javax.swing.ButtonGroup();
        buttonGroupCustomer = new javax.swing.ButtonGroup();
        buttonGroupManager = new javax.swing.ButtonGroup();
        Pane = new javax.swing.JTabbedPane();
        clerk = new javax.swing.JPanel();
        processPurchase = new javax.swing.JRadioButton();
        processReturn = new javax.swing.JRadioButton();
        Purchase = new javax.swing.JPanel();
        cashOrCard = new javax.swing.JComboBox();
        paymentType = new javax.swing.JLabel();
        ccNumber = new javax.swing.JLabel();
        fieldForCC = new javax.swing.JTextField();
        expiryDate = new javax.swing.JLabel();
        fieldforExpiryDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Return = new javax.swing.JPanel();
        customer = new javax.swing.JPanel();
        registration = new javax.swing.JRadioButton();
        purchaseOnline = new javax.swing.JRadioButton();
        manager = new javax.swing.JPanel();
        addItem = new javax.swing.JRadioButton();
        processDelivery = new javax.swing.JRadioButton();
        dailySalesReport = new javax.swing.JRadioButton();
        topSellingItems = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroupClerk.add(processPurchase);
        processPurchase.setText("Process a Purchase");

        buttonGroupClerk.add(processReturn);
        processReturn.setText("Process a Return");
        processReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processReturnActionPerformed(evt);
            }
        });

        Purchase.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase"));
        Purchase.setName(""); // NOI18N

        cashOrCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card" }));
        cashOrCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashOrCardMouseClicked(evt);
            }
        });
        cashOrCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashOrCardActionPerformed(evt);
            }
        });

        paymentType.setText("Payment Type:");

        ccNumber.setText("Credit Card # :");

        fieldForCC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        expiryDate.setText("Expiry Date:");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout PurchaseLayout = new javax.swing.GroupLayout(Purchase);
        Purchase.setLayout(PurchaseLayout);
        PurchaseLayout.setHorizontalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PurchaseLayout.createSequentialGroup()
                        .addComponent(paymentType)
                        .addGap(33, 33, 33)
                        .addComponent(cashOrCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccNumber)
                            .addComponent(expiryDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldForCC)
                            .addGroup(PurchaseLayout.createSequentialGroup()
                                .addComponent(fieldforExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 179, Short.MAX_VALUE))))
                    .addGroup(PurchaseLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(179, 179, 179)))
                .addContainerGap())
        );
        PurchaseLayout.setVerticalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashOrCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentType)
                    .addComponent(ccNumber)
                    .addComponent(fieldForCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiryDate)
                    .addComponent(fieldforExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Return.setBorder(javax.swing.BorderFactory.createTitledBorder("Return"));

        javax.swing.GroupLayout ReturnLayout = new javax.swing.GroupLayout(Return);
        Return.setLayout(ReturnLayout);
        ReturnLayout.setHorizontalGroup(
            ReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ReturnLayout.setVerticalGroup(
            ReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout clerkLayout = new javax.swing.GroupLayout(clerk);
        clerk.setLayout(clerkLayout);
        clerkLayout.setHorizontalGroup(
            clerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(clerkLayout.createSequentialGroup()
                        .addGroup(clerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processReturn)
                            .addComponent(processPurchase))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clerkLayout.setVerticalGroup(
            clerkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(processPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(processReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Pane.addTab("Clerk", clerk);

        buttonGroupCustomer.add(registration);
        registration.setText("Registration");

        buttonGroupCustomer.add(purchaseOnline);
        purchaseOnline.setText("Purchase Items Online");

        javax.swing.GroupLayout customerLayout = new javax.swing.GroupLayout(customer);
        customer.setLayout(customerLayout);
        customerLayout.setHorizontalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registration)
                    .addComponent(purchaseOnline))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        customerLayout.setVerticalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registration)
                .addGap(273, 273, 273)
                .addComponent(purchaseOnline)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        Pane.addTab("Customer", customer);

        buttonGroupManager.add(addItem);
        addItem.setText("Add items to store");

        buttonGroupManager.add(processDelivery);
        processDelivery.setText("Process Delivery");

        buttonGroupManager.add(dailySalesReport);
        dailySalesReport.setText("Daily Sales Report");

        buttonGroupManager.add(topSellingItems);
        topSellingItems.setText("Top Selling Items");

        javax.swing.GroupLayout managerLayout = new javax.swing.GroupLayout(manager);
        manager.setLayout(managerLayout);
        managerLayout.setHorizontalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItem)
                    .addComponent(processDelivery)
                    .addComponent(dailySalesReport)
                    .addComponent(topSellingItems))
                .addGap(0, 555, Short.MAX_VALUE))
        );
        managerLayout.setVerticalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItem)
                .addGap(140, 140, 140)
                .addComponent(processDelivery)
                .addGap(168, 168, 168)
                .addComponent(dailySalesReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(topSellingItems)
                .addGap(151, 151, 151))
        );

        Pane.addTab("Manager", manager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processReturnActionPerformed

    private void cashOrCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashOrCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashOrCardActionPerformed

    private void cashOrCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashOrCardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cashOrCardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Pane;
    private javax.swing.JPanel Purchase;
    private javax.swing.JPanel Return;
    private javax.swing.JRadioButton addItem;
    private javax.swing.ButtonGroup buttonGroupClerk;
    private javax.swing.ButtonGroup buttonGroupCustomer;
    private javax.swing.ButtonGroup buttonGroupManager;
    private javax.swing.JComboBox cashOrCard;
    private javax.swing.JLabel ccNumber;
    private javax.swing.JPanel clerk;
    private javax.swing.JPanel customer;
    private javax.swing.JRadioButton dailySalesReport;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JTextField fieldForCC;
    private javax.swing.JTextField fieldforExpiryDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel manager;
    private javax.swing.JLabel paymentType;
    private javax.swing.JRadioButton processDelivery;
    private javax.swing.JRadioButton processPurchase;
    private javax.swing.JRadioButton processReturn;
    private javax.swing.JRadioButton purchaseOnline;
    private javax.swing.JRadioButton registration;
    private javax.swing.JRadioButton topSellingItems;
    // End of variables declaration//GEN-END:variables
}
